version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDBSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
      - "5000:80"
      - "5001:443"

volumes:
  mongo_data: